#!/bin/bash
set -e

echo ">>> creating databases '${POSTGRES_AUTH_DB}' and '${POSTGRES_APP_DB}'…"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE ${POSTGRES_AUTH_USER} LOGIN PASSWORD '${POSTGRES_AUTH_PASSWORD}';
  CREATE ROLE ${POSTGRES_APP_USER}  LOGIN PASSWORD '${POSTGRES_APP_PASSWORD}';

  CREATE DATABASE ${POSTGRES_AUTH_DB} OWNER ${POSTGRES_AUTH_USER};
  CREATE DATABASE ${POSTGRES_APP_DB}  OWNER ${POSTGRES_APP_USER};
EOSQL

echo ">>> created databases!"