package com.ynixt.sharedfinances.domain.enums

enum class ActionEventCategory {
    BANK_ACCOUNT,
    GROUP,
    GROUP_OWNERSHIP,
    GROUP_MEMBERSHIP,
    CREDIT_CARD,
    BANK_ACCOUNT_ASSOCIATE,
    CREDIT_CARD_ASSOCIATE,
    USER,
    USER_CATEGORY,
    GROUP_CATEGORY,

    WALLET_EVENT,
    SIMULATION_JOB,
    IMPORT_BATCH,
    EXPORT_BATCH,
    ONBOARDING,
    PLAN_USAGE,
    GROUP_PLAN_USAGE,
}
