create table "group_has_users"
(
    id       bigint generated by default as identity primary key not null,
    group_id bigint                                              not null,
    user_id  bigint                                              not null,
    CONSTRAINT fk_group_has_users_group_id
        FOREIGN KEY (group_id)
            REFERENCES "group" (id),
    CONSTRAINT fk_group_has_users_user_id
        FOREIGN KEY (user_id)
            REFERENCES "user" (id)
);