create table "credit_card"(
  id bigint generated by default as identity primary key not null,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone,
  user_id bigint not null,
  name text not null,
  closing_day int not null,
  payment_day int not null,
  "limit" numeric(12,2) not null,
  bill_dates text ARRAY,
  available_limit numeric(12,2),
  enabled boolean not null default true,
  display_on_group boolean not null,
  CONSTRAINT fk_credit_card_user_id
      FOREIGN KEY (user_id)
          REFERENCES "user" (id)
);

CREATE INDEX idx_credit_card_user_id on "credit_card" (user_id);