create table "transaction"
(
    id                    bigint generated by default as identity primary key not null,
    created_at            timestamp with time zone                            not null,
    updated_at            timestamp with time zone,
    user_id               bigint                                              not null,
    type                  text                                                not null,
    category_id           bigint,
    bank_account_id       bigint,
    credit_card_id        bigint,
    description           text,
    credit_card_bill_date text,
    date                  timestamp with time zone                            not null,
    value                 numeric(12, 2)                                      not null,
    installment           int,
    totalInstallments     int,
    CONSTRAINT fk_transaction_user_id
        FOREIGN KEY (user_id)
            REFERENCES "user" (id),
    CONSTRAINT fk_transaction_category_id
        FOREIGN KEY (category_id)
            REFERENCES "transaction_category" (id),
    CONSTRAINT fk_transaction_bank_account_id
        FOREIGN KEY (bank_account_id)
            REFERENCES "bank_account" (id),
    CONSTRAINT fk_transaction_credit_card_id
        FOREIGN KEY (credit_card_id)
            REFERENCES "credit_card" (id)
);

CREATE INDEX idx_transaction_user_id on "transaction" (user_id);
CREATE INDEX idx_transaction_category_id on "transaction" (category_id);
CREATE INDEX idx_transaction_bank_account_id on "transaction" (bank_account_id);
CREATE INDEX idx_transaction_credit_card_id on "transaction" (credit_card_id);