create table "credit_card_bill_date"
(
    id             bigint generated by default as identity primary key not null,
    created_at     timestamp with time zone                            not null,
    updated_at     timestamp with time zone,
    credit_card_id bigint                                              not null,
    bill_date      time                                                not null,
    CONSTRAINT fk_credit_card_bill_date_credit_card
        FOREIGN KEY (credit_card_id)
            REFERENCES "credit_card" (id) ON DELETE CASCADE
);

CREATE INDEX idx_credit_card_bill_date_credit_card on "credit_card_bill_date" (credit_card_id);

alter table "credit_card"
    drop column bill_dates;
alter table "transaction"
    drop column credit_card_bill_date;
alter table "transaction"
    add column credit_card_bill_date_id bigint;
CREATE INDEX idx_transaction_credit_card_bill_date on "transaction" (credit_card_bill_date_id);
alter table "transaction"
    add constraint fk_transaction_credit_card_bill_date foreign key (credit_card_bill_date_id) REFERENCES credit_card_bill_date (id);
