create table "transaction_has_categories"
(
    id             bigint generated by default as identity primary key not null,
    transaction_id bigint                                              not null,
    category_id    bigint                                              not null,
    CONSTRAINT fk_group_has_users_transaction_id
        FOREIGN KEY (transaction_id)
            REFERENCES "transaction" (id) ON DELETE CASCADE,
    CONSTRAINT fk_group_has_users_category_id
        FOREIGN KEY (category_id)
            REFERENCES "transaction_category" (id) ON DELETE CASCADE
);

insert into transaction_has_categories(transaction_id, category_id)
select t.id, t.category_id
from "transaction" t
where t.category_id is not null;

alter table "transaction"
    drop constraint fk_transaction_category_id;
drop index idx_transaction_category_id;

alter table "transaction"
    drop column category_id;
