server:
  port: ${APP_PORT}
  http2:
    enabled: true

spring:
  application:
    name: shared-finances
  r2dbc:
    url: r2dbc:${POSTGRES_APP_CONNECTION_STRING}
    username: ${POSTGRES_APP_USER}
    password: ${POSTGRES_APP_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30s
      max-create-connection-time: 5s
      max-acquire-time: 10s
      validation-query: SELECT 1
      acquire-retry: 2
  flyway:
    url: jdbc:${POSTGRES_APP_CONNECTION_STRING}
    user: ${POSTGRES_APP_USER}
    password: ${POSTGRES_APP_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-missing-locations: false
#    clean-disabled: false
  data:
    redis:
      host: ${REDIS_APP_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 0
      ssl:
        enabled: false
      timeout: 3s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 16
          min-idle: 0
          max-wait: 5s
  web:
    error:
      include-message: always
#  graphql:
#    graphiql:
#      enabled: true
#      path: /open/graphiql

springdoc:
  show-actuator: true
  api-docs:
    path: /open/docs/v3
  swagger-ui:
    path: /open/docs

management:
  endpoints:
    web:
      base-path: /open/actuator

logging:
  level:
    #org.springframework.web: TRACE
#    org.springframework.security: TRACE
#    reactor.netty.http.server: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

app:
  nats:
    url: nats://${NATS_HOST}:${NATS_PORT}
  invitationExpirationMinutes: ${APP_INVITATION_EXPIRATION_MINUTES:15}
  security:
    jwt:
      publicKeyBase64: ${APP_JWT_PUBLIC_KEY}
      privateKeyBase64: ${APP_JWT_PRIVATE_KEY}
      kid: ${APP_JWT_KID}
      issuer: ${APP_JWT_ISSUER}
      accessTokenTTLMinutes: ${APP_JWT_ACCESS_TOKEN_TTL_MINUTES:15}
      refreshTokenTTLMinutes: ${APP_JWT_REFRESH_TOKEN_TTL_MINUTES:43200}
    wrongPasswordTtlMinutes: ${APP_WRONG_PASSWORD_TTL_MINUTES:120}
    wrongPasswordBlock: ${APP_WRONG_PASSWORD_BLOCK:10}
    secureCookie: ${APP_SECURE_COOKIE:true}
    mfa:
      crypto:
        password: ${APP_MFA_TOTP_CRYPTO_PASSWORD}
        saltHex: ${APP_MFA_TOTP_CRYPTO_SALT_HEX}
  s3:
    endpoint: ${APP_S3_ENDPOINT}
    accessKey: ${APP_S3_ACCESS_KEY_ID}
    secretKey: ${APP_S3_SECRET_ACCESS_KEY}
    region: ${APP_S3_REGION}
    bucket: ${APP_S3_BUCKET}
    pathStyleAccessEnabled: ${APP_S3_PATH_STYLE_ACCESS_ENABLED:true}
  exchangeRates:
    providerUrl: ${APP_EXCHANGE_RATES_PROVIDER_URL:https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@}
