server:
  port: ${PORT}
  http2:
    enabled: true
  error:
    include-message: always

spring:
  application:
    name: shared-finances
  r2dbc:
    url: r2dbc:${POSTGRES_APP_CONNECTION_STRING}
    username: ${POSTGRES_APP_USER}
    password: ${POSTGRES_APP_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30s
      max-create-connection-time: 5s
      max-acquire-time: 10s
      validation-query: SELECT 1
      acquire-retry: 2
  flyway:
    url: jdbc:${POSTGRES_APP_CONNECTION_STRING}
    user: ${POSTGRES_APP_USER}
    password: ${POSTGRES_APP_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true
    fail-on-missing-locations: false
  data:
    redis:
      host: ${REDIS_APP_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
      database: 0
      ssl:
        enabled: false
      timeout: 3s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 16
          min-idle: 0
          max-wait: 5s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_ISSUER_URL}
          jwk-set-uri: ${APP_JWK_URL}


logging:
  level:
#    org.springframework.web: TRACE
    org.springframework.security: TRACE
#    reactor.netty.http.server: DEBUG